export type {
  StrategyWorldState,
  StrategyLoadRequest,
  StrategyMapMasterState,
  StrategyForceState,
  StrategyStrongholdState,
  StrategyUnitState,
  StrategyUnitRosterEntry,
  StrategySupplyConvoyState,
  StrategyMessageCarrierState,
  StrategyMessengerState,
  StrategyBattlefieldState,
  StrategyBattlefieldParticipant,
} from "./strategyTypes";

export {
  loadScenario,
  getStrategyState,
  getStrategyMapMaster,
  orderUnitAttack,
  orderUnitSiege,
  mergeUnits,
  splitUnit,
  deployFromStronghold,
  recordEspionageIntel,
  setStrongholdTaxRates,
  setStrongholdGovernancePriority,
  recruitAtStronghold,
  mercenaryRecruitAtStronghold,
  personalRecruit,
  personalMercenaryRecruit,
  appointStrongholdLord,
  transferCharacterToStronghold,
  recallCharacter,
  moveUnit,
  leaveStrongholdAsCharacter,
  moveCharacter,
  enterStrongholdAsCharacter,
  previewCharacterPath,
  previewUnitPath,
  previewBattle,
  executeInstantBattle,
  setUnitDirective,
  advanceDay,
  getMovementTrace,
  getAiDecisionTrace,
  exportStrategySave,
  restoreStrategySave,
  hasLocalStrategySave,
  listStrategySaveSlots,
  saveStrategyToSlot,
  loadStrategyFromSlot,
} from "./strategyClient";

export type { StrategyMovementTraceEntry, StrategyAiDecisionTraceEntry } from "./strategyClient";
export type { StrategySaveSlotSummary } from "./strategyTypes";
export type { StrategyPathPreview, StrategyBattlePreview, StrategyBattleResult, StrategyBattleLogEntry, StrategyInstantBattleResponse, StrategyPolicyChangeResponse, StrategyAdvanceDayResponse, StrategyLordState, StrategyEvent, StrategyEconomySettlementDetail, StrategyEconomyMonthlyDetail, MapPoint } from "./strategyTypes";

export {
  strategyApiDiagnostics,
  setApiMode,
  resolveRequestUrl,
  STRATEGY_API_PREFIX,
  type StrategyApiMode,
} from "./strategyDiagnostics";
